project:
  type: website
  output-dir: _html
  render:
    - "*.qmd"
    - "notes/**/*.qmd"
    - "presentations/**/*.qmd"

execute:
  freeze: auto

format:
  html:
    title-block-style: none
    theme:
      light: [flatly, "style/light-theme.scss", "style/shared.scss"]
      dark: [darkly, "style/dark-theme.scss", "style/shared.scss"]
    toc: true
    toc-depth: 5
    toc-location: left
    toc-float: true
    number-sections: false
    code-copy: true
    from: markdown+emoji
    link-external-icon: true
    link-external-newwindow: true
    code-block-bg: true
    code-block-border-left: "#00549F"
    highlight-style: github
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          MathJax = {
            tex: {
              tags: 'ams'
            }
          };
          </script>

website:
  favicon: "assets/TruhnLab.png"
  search:
    location: navbar
    type: overlay
  navbar:
    title: false
    logo: assets/TruhnLab.png
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Meetings"
        href: notes/meetings.qmd
      - text: "Presentation"
        href: presentations/index.qmd
    right:
      - icon: github
        href: https://github.com/gary8564/MedSliM

  repo-url: https://github.com/gary8564/PostMA_Discussion
  repo-actions: [edit, issue]
