name: plotting_tools
channels:
  - conda-forge
dependencies:
  - ipykernel
  - jupyter
  - jupyterlab
  - nbclient
  - nbformat
  - matplotlib
  - seaborn
  - plotly
  - numpy
  - pandas
  - python=3.12
  - pyyaml
  - scikit-learn
  - scipy
